# Generated by Django 5.0.6 on 2024-07-18 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0005_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='user',
            field=models.OneToOneField(default=2, limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
