# Generated by Django 5.0.6 on 2024-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_branch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
        migrations.AddField(
            model_name='branch',
            name='user_type',
            field=models.IntegerField(default=2),
        ),
    ]
