# Generated by Django 5.0.6 on 2024-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_branch_user_branch_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='user_name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
