# Generated by Django 5.1 on 2024-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_branch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
