# Generated by Django 5.1 on 2024-08-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_branch_email_branch_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='email',
            new_name='emails',
        ),
    ]
