# Generated by Django 5.0.6 on 2024-07-18 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousJob',
            fields=[
                ('previousJob_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('portofolio', models.CharField(max_length=100)),
                ('Certificate', models.CharField(max_length=100)),
                ('recomendation', models.CharField(max_length=100)),
                ('jobNature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobnature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate', models.CharField(max_length=100)),
                ('portofolio', models.CharField(max_length=100)),
                ('started_at', models.DateField()),
                ('jobNature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobnature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
