# Generated by Django 5.0.6 on 2024-07-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousjob',
            old_name='Certificate',
            new_name='description',
        ),
    ]
