# Generated by Django 5.0.6 on 2024-07-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_rename_certificate_previousjob_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='portofolio',
            new_name='portfolio',
        ),
        migrations.RemoveField(
            model_name='previousjob',
            name='portofolio',
        ),
        migrations.RemoveField(
            model_name='previousjob',
            name='recomendation',
        ),
        migrations.AddField(
            model_name='previousjob',
            name='portfolio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='previousjob',
            name='recommendation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previousjob',
            name='description',
            field=models.TextField(),
        ),
    ]
