# Generated by Django 5.0.6 on 2024-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_portofolio_skill_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='certificate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='portfolio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
