# Generated by Django 5.0.7 on 2024-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_description_alter_skill_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='previousjob',
            name='job_name',
            field=models.CharField(default='some job', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='skill', max_length=255),
        ),
    ]
