# Generated by Django 5.0.7 on 2024-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_skill_certificate_remove_skill_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
