# Generated by Django 5.0.7 on 2024-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_skill_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousjob',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
