# Generated by Django 5.0.7 on 2024-07-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_previousjob_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousjob',
            name='experience',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.FloatField(default=1),
        ),
    ]
