# Generated by Django 5.0.7 on 2024-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_previousjob_experience_alter_skill_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousjob',
            name='company',
            field=models.CharField(default='Company', max_length=255),
        ),
    ]
