# Generated by Django 5.0.7 on 2024-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_alter_previousjob_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousjob',
            name='recommendation',
            field=models.TextField(null=True),
        ),
    ]
