# Generated by Django 5.0.7 on 2024-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_alter_previousjob_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousjob',
            name='job',
            field=models.CharField(default='Front End Developer', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(default='Front End Developer', max_length=255),
        ),
    ]
