# Generated by Django 5.0.6 on 2024-07-18 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNature',
            fields=[
                ('jobNature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobAnnouncement',
            fields=[
                ('jobAnnouncment_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('jobNature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobnature')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('appliedJob_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Waiting', max_length=10)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('jobAnnouncement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobannouncement')),
            ],
        ),
    ]
