# Generated by Django 5.0.6 on 2024-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobannouncement',
            old_name='jobAnnouncment_id',
            new_name='jobAnnouncement_id',
        ),
        migrations.AddField(
            model_name='jobannouncement',
            name='educationLevel',
            field=models.CharField(default='Bachelor', max_length=50),
        ),
        migrations.AddField(
            model_name='jobannouncement',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobannouncement',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=10),
        ),
        migrations.AddField(
            model_name='jobannouncement',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobannouncement',
            name='salary',
            field=models.CharField(default='Decided After The Interview', max_length=255),
        ),
        migrations.AddField(
            model_name='jobannouncement',
            name='type_of_employment',
            field=models.CharField(default='Full-time', max_length=50),
        ),
    ]
