# Generated by Django 5.0.7 on 2024-07-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_jobannouncment_id_jobannouncement_jobannouncement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobannouncement',
            name='image_path',
        ),
    ]
