# Generated by Django 5.0.7 on 2024-07-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_jobannouncement_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobannouncement',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobannouncement',
            name='main_skill',
            field=models.CharField(default='employee', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobannouncement',
            name='soft_skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
