# Generated by Django 5.0.7 on 2024-07-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobannouncement_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobannouncement',
            name='image_path',
        ),
    ]
