# Generated by Django 5.0.7 on 2024-07-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_jobannouncement_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobannouncement',
            name='salary',
            field=models.FloatField(),
        ),
    ]
