# Generated by Django 5.0.7 on 2024-08-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobannouncement_salary'),
        ('users', '0011_user_instagram_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('job_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobannouncement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
