# Generated by Django 5.0.7 on 2024-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='status',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('To be Interviewed', 'To be Interviewed')], default='Waiting', max_length=17),
        ),
    ]
