# Generated by Django 5.0.6 on 2024-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='behance_link',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Aleppo', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.CharField(default='default_facebook_link', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='github_link',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
