# Generated by Django 5.0.6 on 2024-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_behance_link_user_city_user_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='choose', max_length=10),
        ),
    ]
