# Generated by Django 5.0.6 on 2024-07-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='user',
            name='educationLevel',
            field=models.CharField(default='Bachelor', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='ian', max_length=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
