# Generated by Django 5.0.7 on 2024-08-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_instagram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='educationLevel',
            field=models.CharField(default='Bachelor', max_length=25),
        ),
    ]
